spring.application.name=blogapp
#spring.application.name=newProjectLogin
spring.datasource.url=jdbc:mysql://localhost:3306/flightbooking
spring.datasource.username=root
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=update
server.port=8081